// Date: 6/5/2013 12:22:10 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelUZI extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape4;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape4;
    ModelRenderer Shape4;
    ModelRenderer Shape3;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
  
  public ModelUZI()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 44, 21);
      Shape1.addBox(-2F, -4F, -1.5F, 5, 8, 3);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, -0.1745329F);
      Shape4 = new ModelRenderer(this, 52, 0);
      Shape4.addBox(-10.05333F, 7.32F, -1F, 4, 4, 2);
      Shape4.setRotationPoint(0F, 0F, 0F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0.3665191F);
      Shape2 = new ModelRenderer(this, 0, 15);
      Shape2.addBox(-28F, -9.06F, -2F, 16, 4, 4);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 40, 26);
      Shape2.addBox(-29F, -9F, -0.5F, 1, 1, 1);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 40, 26);
      Shape2.addBox(-33F, -12.50667F, -0.5F, 1, 5, 1);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 40, 26);
      Shape2.addBox(-32F, -12F, -0.5F, 1, 1, 1);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 36, 0);
      Shape4.addBox(-11.5F, -2F, -1.5F, 5, 4, 3);
      Shape4.setRotationPoint(0F, 0F, 0F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0.1908227F);
      Shape4 = new ModelRenderer(this, 52, 0);
      Shape4.addBox(-10.5F, 2F, -1F, 4, 5, 2);
      Shape4.setRotationPoint(0F, 0F, 0F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0.296706F);
      Shape3 = new ModelRenderer(this, 0, 23);
      Shape3.addBox(10F, -9F, -1F, 6, 7, 2);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 40, 26);
      Shape2.addBox(-30F, -10F, -0.5F, 1, 1, 1);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 44, 15);
      Shape3.addBox(0.6933333F, -12.14667F, -1F, 2, 4, 2);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, -0.122173F);
      Shape3 = new ModelRenderer(this, 2, 25);
      Shape3.addBox(2F, -9F, -1F, 4, 5, 2);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 2, 24);
      Shape3.addBox(6F, -9F, -1F, 4, 6, 2);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 26, 11);
      Shape2.addBox(-41F, -8F, -1F, 13, 2, 2);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 11);
      Shape3.addBox(-10F, -15F, -1F, 11, 2, 2);
      Shape3.setRotationPoint(0F, 2F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 40, 26);
      Shape2.addBox(-31F, -11F, -0.5F, 1, 1, 1);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 52, 15);
      Shape3.addBox(-13F, -9.52F, -1F, 1, 4, 2);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0.2617994F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(-12F, -9F, -2F, 14, 6, 4);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape4.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape4.render(f5);
    Shape4.render(f5);
    Shape3.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
