// Date: 5/30/2013 9:16:25 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelMr. Handy extends ModelBase
{
  //fields
    ModelRenderer Rumf_1;
    ModelRenderer Arm_1.1;
    ModelRenderer Rumf_2;
    ModelRenderer Arm_1.2;
    ModelRenderer Arm_1.3;
    ModelRenderer Arm_1.4;
    ModelRenderer Arm_1.5;
    ModelRenderer Arm_1.6;
    ModelRenderer Auge_1.1;
    ModelRenderer Auge_1.2;
    ModelRenderer Auge_1.3;
    ModelRenderer Arm_2.1;
    ModelRenderer Arm_3.1;
    ModelRenderer Arm_2.2;
    ModelRenderer Arm_3.2;
    ModelRenderer Arm_2.3;
    ModelRenderer Arm_3.3;
    ModelRenderer Arm_2.4;
    ModelRenderer Arm_3.4;
    ModelRenderer Arm_2.5;
    ModelRenderer Arm_3.5;
    ModelRenderer Arm_2.6;
    ModelRenderer Arm_3.6;
    ModelRenderer Arm_3.7;
    ModelRenderer Auge_2.1;
    ModelRenderer Auge_3.1;
    ModelRenderer Auge_2.2;
    ModelRenderer Auge_3.2;
    ModelRenderer Auge_2.3;
    ModelRenderer Auge_3.3;
  
  public ModelMr. Handy()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Rumf_1 = new ModelRenderer(this, 12, 23);
      Rumf_1.addBox(-5F, 0F, -5F, 10, 10, 10);
      Rumf_1.setRotationPoint(0F, -6F, 0F);
      Rumf_1.setTextureSize(64, 64);
      Rumf_1.mirror = true;
      setRotation(Rumf_1, 0F, 0F, 0F);
      Arm_1.1 = new ModelRenderer(this, 22, 44);
      Arm_1.1.addBox(0F, 0F, 0F, 7, 2, 2);
      Arm_1.1.setRotationPoint(-1F, 3F, -5F);
      Arm_1.1.setTextureSize(64, 64);
      Arm_1.1.mirror = true;
      setRotation(Arm_1.1, 0F, 1.570796F, 0.7853982F);
      Rumf_2 = new ModelRenderer(this, 0, 0);
      Rumf_2.addBox(0F, 0F, 0F, 4, 7, 4);
      Rumf_2.setRotationPoint(-2F, 3F, -2F);
      Rumf_2.setTextureSize(64, 64);
      Rumf_2.mirror = true;
      setRotation(Rumf_2, 0F, 0F, 0F);
      Arm_1.2 = new ModelRenderer(this, 22, 49);
      Arm_1.2.addBox(0F, 0F, 0F, 2, 7, 2);
      Arm_1.2.setRotationPoint(-1F, 8F, -10F);
      Arm_1.2.setTextureSize(64, 64);
      Arm_1.2.mirror = true;
      setRotation(Arm_1.2, 0.5585054F, 0F, 0F);
      Arm_1.3 = new ModelRenderer(this, 31, 49);
      Arm_1.3.addBox(0F, 0F, 0F, 2, 6, 2);
      Arm_1.3.setRotationPoint(-1F, 12F, -6F);
      Arm_1.3.setTextureSize(64, 64);
      Arm_1.3.mirror = true;
      setRotation(Arm_1.3, -0.4712389F, 0F, 0F);
      Arm_1.4 = new ModelRenderer(this, 40, 56);
      Arm_1.4.addBox(0F, 0F, 0F, 2, 6, 2);
      Arm_1.4.setRotationPoint(-1F, 16F, -7F);
      Arm_1.4.setTextureSize(64, 64);
      Arm_1.4.mirror = true;
      setRotation(Arm_1.4, -1.448623F, 0F, 0F);
      Arm_1.5 = new ModelRenderer(this, 17, 56);
      Arm_1.5.addBox(0F, -7F, 0F, 1, 7, 1);
      Arm_1.5.setRotationPoint(-0.5F, 18F, -13F);
      Arm_1.5.setTextureSize(64, 64);
      Arm_1.5.mirror = true;
      setRotation(Arm_1.5, 0.2268928F, 0F, 0F);
      Arm_1.6 = new ModelRenderer(this, 25, 59);
      Arm_1.6.addBox(0F, 0F, 0F, 3, 1, 3);
      Arm_1.6.setRotationPoint(0F, 11F, -13F);
      Arm_1.6.setTextureSize(64, 64);
      Arm_1.6.mirror = true;
      setRotation(Arm_1.6, 0.1047198F, 2.356194F, -0.1047198F);
      Auge_1.1 = new ModelRenderer(this, 30, 0);
      Auge_1.1.addBox(-1.5F, 0F, -6F, 3, 1, 6);
      Auge_1.1.setRotationPoint(0F, -3F, -5F);
      Auge_1.1.setTextureSize(64, 64);
      Auge_1.1.mirror = true;
      setRotation(Auge_1.1, 0.7853982F, 0F, 0F);
      Auge_1.2 = new ModelRenderer(this, 30, 8);
      Auge_1.2.addBox(0F, 0F, -6F, 3, 1, 6);
      Auge_1.2.setRotationPoint(-1.5F, 2F, -8F);
      Auge_1.2.setTextureSize(64, 64);
      Auge_1.2.mirror = true;
      setRotation(Auge_1.2, -1.396263F, 0F, 0F);
      Auge_1.3 = new ModelRenderer(this, 33, 16);
      Auge_1.3.addBox(0F, 0F, 0F, 3, 3, 3);
      Auge_1.3.setRotationPoint(-1.5F, -5F, -12F);
      Auge_1.3.setTextureSize(64, 64);
      Auge_1.3.mirror = true;
      setRotation(Auge_1.3, 0F, 0F, 0F);
      Arm_2.1 = new ModelRenderer(this, 1, 18);
      Arm_2.1.addBox(0F, 0F, -1F, 7, 2, 2);
      Arm_2.1.setRotationPoint(-5F, 3F, 5F);
      Arm_2.1.setTextureSize(64, 64);
      Arm_2.1.mirror = true;
      setRotation(Arm_2.1, 0F, -2.530727F, 0.7853982F);
      Arm_3.1 = new ModelRenderer(this, 46, 18);
      Arm_3.1.addBox(0F, 0F, -1F, 7, 2, 2);
      Arm_3.1.setRotationPoint(5F, 3F, 5F);
      Arm_3.1.setTextureSize(64, 64);
      Arm_3.1.mirror = true;
      setRotation(Arm_3.1, 0F, -0.7853982F, 0.7853982F);
      Arm_2.2 = new ModelRenderer(this, 1, 23);
      Arm_2.2.addBox(-1F, 0F, 0F, 2, 7, 2);
      Arm_2.2.setRotationPoint(-9F, 8F, 8F);
      Arm_2.2.setTextureSize(64, 64);
      Arm_2.2.mirror = true;
      setRotation(Arm_2.2, 0.5585054F, 2.199115F, 0F);
      Arm_3.2 = new ModelRenderer(this, 55, 23);
      Arm_3.2.addBox(-1F, 0F, 0F, 2, 7, 2);
      Arm_3.2.setRotationPoint(8F, 8F, 8F);
      Arm_3.2.setTextureSize(64, 64);
      Arm_3.2.mirror = true;
      setRotation(Arm_3.2, 0.5585054F, -2.343285F, 0F);
      Arm_2.3 = new ModelRenderer(this, 1, 33);
      Arm_2.3.addBox(-1F, 0F, 0F, 2, 6, 2);
      Arm_2.3.setRotationPoint(-6F, 12F, 6F);
      Arm_2.3.setTextureSize(64, 64);
      Arm_2.3.mirror = true;
      setRotation(Arm_2.3, -0.4712389F, 2.1734F, 0F);
      Arm_3.3 = new ModelRenderer(this, 55, 33);
      Arm_3.3.addBox(-1F, 0F, 0F, 2, 6, 2);
      Arm_3.3.setRotationPoint(5.5F, 12F, 5.5F);
      Arm_3.3.setTextureSize(64, 64);
      Arm_3.3.mirror = true;
      setRotation(Arm_3.3, -0.4712389F, -2.324696F, 0F);
      Arm_2.4 = new ModelRenderer(this, 1, 42);
      Arm_2.4.addBox(-1F, 0F, 0F, 2, 6, 2);
      Arm_2.4.setRotationPoint(-7F, 16F, 6.5F);
      Arm_2.4.setTextureSize(64, 64);
      Arm_2.4.mirror = true;
      setRotation(Arm_2.4, -1.448623F, 2.190847F, 0F);
      Arm_3.4 = new ModelRenderer(this, 55, 42);
      Arm_3.4.addBox(-1F, 0F, 0F, 2, 6, 2);
      Arm_3.4.setRotationPoint(6F, 16F, 6F);
      Arm_3.4.setTextureSize(64, 64);
      Arm_3.4.mirror = true;
      setRotation(Arm_3.4, -1.448623F, -2.337823F, 0F);
      Arm_2.5 = new ModelRenderer(this, 1, 51);
      Arm_2.5.addBox(-1F, 0F, 0F, 1, 7, 1);
      Arm_2.5.setRotationPoint(-11.5F, 18.06667F, 10F);
      Arm_2.5.setTextureSize(64, 64);
      Arm_2.5.mirror = true;
      setRotation(Arm_2.5, 2.879793F, -0.9369662F, 0F);
      Arm_3.5 = new ModelRenderer(this, 59, 51);
      Arm_3.5.addBox(0F, 0F, 0F, 1, 7, 1);
      Arm_3.5.setRotationPoint(10F, 18F, 11F);
      Arm_3.5.setTextureSize(64, 64);
      Arm_3.5.mirror = true;
      setRotation(Arm_3.5, 2.879793F, 0.7532474F, 0F);
      Arm_2.6 = new ModelRenderer(this, 6, 51);
      Arm_2.6.addBox(0F, 0F, 0F, 0, 4, 4);
      Arm_2.6.setRotationPoint(-12F, 12F, 10F);
      Arm_2.6.setTextureSize(64, 64);
      Arm_2.6.mirror = true;
      setRotation(Arm_2.6, 1.134464F, -0.9773844F, 0F);
      Arm_3.6 = new ModelRenderer(this, 50, 58);
      Arm_3.6.addBox(0F, 0F, 0F, 2, 3, 2);
      Arm_3.6.setRotationPoint(10F, 12F, 10F);
      Arm_3.6.setTextureSize(64, 64);
      Arm_3.6.mirror = true;
      setRotation(Arm_3.6, 0F, 0F, 0F);
      Arm_3.7 = new ModelRenderer(this, 40, 48);
      Arm_3.7.addBox(0F, 0F, 0F, 1, 1, 6);
      Arm_3.7.setRotationPoint(10F, 11F, 10.5F);
      Arm_3.7.setTextureSize(64, 64);
      Arm_3.7.mirror = true;
      setRotation(Arm_3.7, 0F, 0.8028515F, 0F);
      Auge_2.1 = new ModelRenderer(this, 30, 0);
      Auge_2.1.addBox(0F, 0F, 0F, 3, 1, 6);
      Auge_2.1.setRotationPoint(-9F, 1F, 2F);
      Auge_2.1.setTextureSize(64, 64);
      Auge_2.1.mirror = true;
      setRotation(Auge_2.1, 0.7853982F, 1.570796F, 0F);
      Auge_3.1 = new ModelRenderer(this, 30, 0);
      Auge_3.1.addBox(0F, 0F, 0F, 3, 1, 6);
      Auge_3.1.setRotationPoint(9F, 1F, -1F);
      Auge_3.1.setTextureSize(64, 64);
      Auge_3.1.mirror = true;
      setRotation(Auge_3.1, 0.7853982F, -1.570796F, 0F);
      Auge_2.2 = new ModelRenderer(this, 30, 8);
      Auge_2.2.addBox(0F, 0F, 0F, 3, 1, 6);
      Auge_2.2.setRotationPoint(-9F, -4F, 2F);
      Auge_2.2.setTextureSize(64, 64);
      Auge_2.2.mirror = true;
      setRotation(Auge_2.2, -1.396263F, 1.570796F, 0F);
      Auge_3.2 = new ModelRenderer(this, 30, 8);
      Auge_3.2.addBox(0F, 0F, 0F, 3, 1, 6);
      Auge_3.2.setRotationPoint(9F, -4F, -1F);
      Auge_3.2.setTextureSize(64, 64);
      Auge_3.2.mirror = true;
      setRotation(Auge_3.2, -1.396263F, -1.570796F, 0F);
      Auge_2.3 = new ModelRenderer(this, 33, 16);
      Auge_2.3.addBox(-3F, 0F, 0F, 3, 3, 3);
      Auge_2.3.setRotationPoint(-12F, -5F, -1F);
      Auge_2.3.setTextureSize(64, 64);
      Auge_2.3.mirror = true;
      setRotation(Auge_2.3, 0F, 1.570796F, 0F);
      Auge_3.3 = new ModelRenderer(this, 33, 16);
      Auge_3.3.addBox(0F, 0F, -3F, 3, 3, 3);
      Auge_3.3.setRotationPoint(9F, -5F, -1F);
      Auge_3.3.setTextureSize(64, 64);
      Auge_3.3.mirror = true;
      setRotation(Auge_3.3, 0F, -1.570796F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Rumf_1.render(f5);
    Arm_1.1.render(f5);
    Rumf_2.render(f5);
    Arm_1.2.render(f5);
    Arm_1.3.render(f5);
    Arm_1.4.render(f5);
    Arm_1.5.render(f5);
    Arm_1.6.render(f5);
    Auge_1.1.render(f5);
    Auge_1.2.render(f5);
    Auge_1.3.render(f5);
    Arm_2.1.render(f5);
    Arm_3.1.render(f5);
    Arm_2.2.render(f5);
    Arm_3.2.render(f5);
    Arm_2.3.render(f5);
    Arm_3.3.render(f5);
    Arm_2.4.render(f5);
    Arm_3.4.render(f5);
    Arm_2.5.render(f5);
    Arm_3.5.render(f5);
    Arm_2.6.render(f5);
    Arm_3.6.render(f5);
    Arm_3.7.render(f5);
    Auge_2.1.render(f5);
    Auge_3.1.render(f5);
    Auge_2.2.render(f5);
    Auge_3.2.render(f5);
    Auge_2.3.render(f5);
    Auge_3.3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
